### ISSUE TITLE
Putting random values into hex code and appvar error

### ISSUE THREAD

**Issue by infinitypacific** [Captain-Calc/HexaEdit-CE#1]
When I put this on an emulator it works perfectly but whenever I run it on real hardware and try to edit something, after saving it and reentering it it comes up with a bunch of random hex values but the same amount of bytes. Also whenever I exit the app it says "Warning: Cannot save Recents appvar" I think that's HXAEDITr. I deleted the appvars and reinstalled it but nothing changed.

**Comment by captain-calc** [comment]
If you archive HexaEdit and every other program/appvar on your calculator, do you still have the same issue? HexaEdit 3 creates a large appvar when it starts up that consumes as much free memory as it can to avoid dynamic memory allocation. When you run the test, make sure you have at least 90,000 bytes of free RAM available.

**Comment by infinitypacific** [comment]
I did have enough RAM for it but it kept doing the same thing. Also I reset the ram and it somehow fixed the recent appvar warning. I also have to press 2nd or enter multiple times for the insert button to work. Here's a video of what I did:
https://github.com/captain-calc/HexaEdit-CE/assets/87620151/bbf473cc-0785-4ed0-a508-8b27ba5b7533

**Comment by infinitypacific** [comment]
Also for some reason, it's grey instead of green. I don't know if that's significant, but on the emulator I ran it on, it's green.

**Comment by captain-calc** [comment]
I have isolated the issue requiring the multiple keypresses when using the "Insert" tool and will fix it.

When you say "it's grey instead of green", do you mean that HexaEdit uses green colors in the emulator and grey colors on the actual hardware? HexaEdit is supposed to use a grey colorscheme by default.
